# u-boot&&fsbl编译流程学习
[1;34;47m Run build_fsbl() function [0m
#build_fsbl步骤依赖于u-boot-dts和 u-boot-build

#
[1;36;40m  [TARGET] u-boot-dts [0m
find /project/sophon/build/boards/sophon/edge_wevb_emmc \
	\( -path "*linux/*.dts*" -o -path "*dts_arm64/*.dts*" \) \
	-exec cp {} /project/sophon/u-boot-2021.10/arch/arm/dts/ \;
find /project/sophon/build/boards/default/dts/sophon /project/sophon/build/boards/default/dts/sophon_arm64 -name *.dts* -exec cp {} /project/sophon/u-boot-2021.10/arch/arm/dts/ \;





[1;36;40m  [TARGET] u-boot-build [0m
ln -snrf /project/sophon/build/output/edge_wevb_emmc/cvi_board_memmap.h /project/sophon/u-boot-2021.10/include/
rm -f /project/sophon/u-boot-2021.10/board/cvitek/cvi_board_init.c
ln -s /project/sophon/build/boards/sophon/edge_wevb_emmc/u-boot/cvi_board_init.c /project/sophon/u-boot-2021.10/board/cvitek/cvi_board_init.c
rm -f /project/sophon/u-boot-2021.10/include/cvitek/cvitek.h
ln -s /project/sophon/build/boards/sophon/edge_wevb_emmc/u-boot/cvitek.h /project/sophon/u-boot-2021.10/include/cvitek/cvitek.h
sed -i "s/CONFIG_ROOTFS_UBUNTU=n/CONFIG_ROOTFS_UBUNTU=y/g" /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/.config

#生成.config
make -j48 -C /project/sophon/u-boot-2021.10 olddefconfig
make[1]: Entering directory '/project/sophon/u-boot-2021.10'
make[2]: Entering directory '/project/sophon/u-boot-2021.10/build/edge_wevb_emmc'
  GEN     Makefile
scripts/kconfig/conf  --olddefconfig Kconfig
#
# configuration written to .config
#
make[2]: Leaving directory '/project/sophon/u-boot-2021.10/build/edge_wevb_emmc'
make[1]: Leaving directory '/project/sophon/u-boot-2021.10'


make -j48 -C /project/sophon/u-boot-2021.10 V=1 all
make[1]: Entering directory '/project/sophon/u-boot-2021.10'
#-C 切换路径，生成文件保存在该路径下（构建路径）   KBUILD_SRC 指定源码路径 -f 指定makefile路径
make -C /project/sophon/u-boot-2021.10/build/edge_wevb_emmc KBUILD_SRC=/project/sophon/u-boot-2021.10 \
-f /project/sophon/u-boot-2021.10/Makefile all
make[2]: Entering directory '/project/sophon/u-boot-2021.10/build/edge_wevb_emmc'
#基于当前目录下已有的 .config文件，来生成所有编译所需的派生文件和头文件（主要是 autoconf.h和 auto.conf），并清理任何过时的配置选项
make -f /project/sophon/u-boot-2021.10/Makefile syncconfig
#obj 指定源码路径和生成文件存放路径 ；fixdep​​ 是此命令最重要的编译产出，用于​​处理 C 源代码的依赖关系​​
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts/basic
ln -fsn /project/sophon/u-boot-2021.10 source
#指定bash执行mkmakefile脚本，参数/project/sophon/u-boot-2021.10指明了 U-Boot ​​源代码的根目录
#该脚本在构建路径下生成一个 代理Makefile，功能：可以在构建目录下输入和在源码目录中编译时完全一样的命令
/bin/bash /project/sophon/u-boot-2021.10/scripts/mkmakefile /project/sophon/u-boot-2021.10
rm -f .tmp_quiet_recordmcount
  GEN     Makefile
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts/kconfig syncconfig
scripts/kconfig/conf  --syncconfig Kconfig
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.autoconf || \
	{ rm -f include/config/auto.conf; false; }
mkdir -p include/asm
if [ -d /project/sophon/u-boot-2021.10/arch/arm/mach-/include/mach ]; then	\
	dest=arch/arm/mach-/include/mach;			\
else									\
	dest=arch/arm/include/asm/arch-armv8;	\
fi;									\
ln -fsn /project/sophon/u-boot-2021.10/$dest include/asm/arch
set -e; mkdir -p include/; 	(echo "/* Automatically generated - do not edit */"; for i in $(echo "" | sed 's/,/ /g'); do echo \#define CONFIG_$i | sed '/=/ {s/=/	/;q; } ; { s/$/	1/; }'; done; echo \#define CONFIG_BOARDDIR board/cvitek/cv186x; echo \#include \<config_uncmd_spl.h\>; echo \#include \<configs/"cv186x-asic".h\>; echo \#include \<asm/config.h\>; echo \#include \<linux/kconfig.h\>; echo \#include \<config_fallbacks.h\>;) < /project/sophon/u-boot-2021.10/scripts/Makefile.autoconf > include/config.h.tmp; if [ -r include/config.h ] && cmp -s include/config.h include/config.h.tmp; then rm -f include/config.h.tmp; else : '  UPD     include/config.h'; mv -f include/config.h.tmp include/config.h; fi
  aarch64-none-linux-gnu-gcc -E -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned  -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394     -D__ARM__           -fno-pic  -mstrict-align  -ffunction-sections -fdata-sections -fno-common -ffixed-r9     -fno-common -ffixed-x18 -pipe -Iinclude  -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include  -DDO_DEPS_ONLY -dM /project/sophon/u-boot-2021.10/include/common.h > u-boot.cfg.tmp && { grep 'define CONFIG_' u-boot.cfg.tmp > u-boot.cfg; rm u-boot.cfg.tmp; } || { rm u-boot.cfg.tmp; false; }
  aarch64-none-linux-gnu-gcc -x c -DDO_DEPS_ONLY -M -MP -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned  -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394     -D__ARM__           -fno-pic  -mstrict-align  -ffunction-sections -fdata-sections -fno-common -ffixed-r9     -fno-common -ffixed-x18 -pipe -Iinclude  -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -MQ include/config/auto.conf /project/sophon/u-boot-2021.10/include/common.h > include/autoconf.mk.dep || { rm include/autoconf.mk.dep; false; }
  sed -n -f /project/sophon/u-boot-2021.10/tools/scripts/define2mk.sed u-boot.cfg | while read line; do if [ -n "" ] || ! grep -q "${line%=*}=" include/config/auto.conf; then echo "$line"; fi done > include/autoconf.mk
touch include/config/auto.conf
set -e; mkdir -p include/config/; 	echo "2021.10$(/bin/bash /project/sophon/u-boot-2021.10/scripts/setlocalversion /project/sophon/u-boot-2021.10)" < include/config/auto.conf > include/config/uboot.release.tmp; if [ -r include/config/uboot.release ] && cmp -s include/config/uboot.release include/config/uboot.release.tmp; then rm -f include/config/uboot.release.tmp; else : '  UPD     include/config/uboot.release'; mv -f include/config/uboot.release.tmp include/config/uboot.release; fi
ln -fsn /project/sophon/u-boot-2021.10 source
set -e; mkdir -p include/generated/; 	(if test -n "${SOURCE_DATE_EPOCH}"; then SOURCE_DATE="@${SOURCE_DATE_EPOCH}"; DATE=""; for date in gdate date.gnu date; do ${date} -u -d "${SOURCE_DATE}" >/dev/null 2>&1 && DATE="${date}"; done; if test -n "${DATE}"; then LC_ALL=C ${DATE} -u -d "${SOURCE_DATE}" +'#define U_BOOT_DATE "%b %d %C%y"'; LC_ALL=C ${DATE} -u -d "${SOURCE_DATE}" +'#define U_BOOT_TIME "%T"'; LC_ALL=C ${DATE} -u -d "${SOURCE_DATE}" +'#define U_BOOT_TZ "%z"'; LC_ALL=C ${DATE} -u -d "${SOURCE_DATE}" +'#define U_BOOT_BUILD_DATE 0x%Y%m%d'; LC_ALL=C ${DATE} -u -d "${SOURCE_DATE}" +'#define U_BOOT_EPOCH %s'; else return 42; fi; else LC_ALL=C date +'#define U_BOOT_DATE "%b %d %C%y"'; LC_ALL=C date +'#define U_BOOT_TIME "%T"'; LC_ALL=C date +'#define U_BOOT_TZ "%z"'; LC_ALL=C date +'#define U_BOOT_BUILD_DATE 0x%Y%m%d'; LC_ALL=C date +'#define U_BOOT_EPOCH %s'; fi) < /project/sophon/u-boot-2021.10/Makefile > include/generated/timestamp_autogenerated.h.tmp; if [ -r include/generated/timestamp_autogenerated.h ] && cmp -s include/generated/timestamp_autogenerated.h include/generated/timestamp_autogenerated.h.tmp; then rm -f include/generated/timestamp_autogenerated.h.tmp; else : '  UPD     include/generated/timestamp_autogenerated.h'; mv -f include/generated/timestamp_autogenerated.h.tmp include/generated/timestamp_autogenerated.h; fi
/bin/bash /project/sophon/u-boot-2021.10/scripts/mkmakefile /project/sophon/u-boot-2021.10
set -e; mkdir -p include/generated/; 	(if test -n "${DEVICE_TREE}"; then echo \#define DEVICE_TREE \"\"; else echo \#define DEVICE_TREE CONFIG_DEFAULT_DEVICE_TREE; fi) < /project/sophon/u-boot-2021.10/Makefile > include/generated/dt.h.tmp; if [ -r include/generated/dt.h ] && cmp -s include/generated/dt.h include/generated/dt.h.tmp; then rm -f include/generated/dt.h.tmp; else : '  UPD     include/generated/dt.h'; mv -f include/generated/dt.h.tmp include/generated/dt.h; fi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts/basic
  GEN     Makefile
  /project/sophon/u-boot-2021.10/scripts/check-config.sh u-boot.cfg /project/sophon/u-boot-2021.10/scripts/config_whitelist.txt /project/sophon/u-boot-2021.10
rm -f .tmp_quiet_recordmcount
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts/dtc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=scripts/dtc
if [ -f /project/sophon/u-boot-2021.10/.config -o -d /project/sophon/u-boot-2021.10/include/config ]; then \
	echo >&2 "  /project/sophon/u-boot-2021.10 is not clean, please run 'make mrproper'"; \
	echo >&2 "  in the '/project/sophon/u-boot-2021.10' directory.";\
	/bin/false; \
fi;
set -e; mkdir -p include/generated/; 	(echo \#define PLAIN_VERSION \"2021.10""-g77795a14ce-dirty\"; echo \#define U_BOOT_VERSION \"U-Boot \" PLAIN_VERSION; echo \#define U_BOOT_VERSION_NUM 2021; echo \#define U_BOOT_VERSION_NUM_PATCH $(echo 10 | sed -e "s/^0*//"); echo \#define CC_VERSION_STRING \"$(LC_ALL=C aarch64-none-linux-gnu-gcc --version | head -n 1)\"; echo \#define LD_VERSION_STRING \"$(LC_ALL=C aarch64-none-linux-gnu-ld.bfd --version | head -n 1)\"; ) < include/config/uboot.release > include/generated/version_autogenerated.h.tmp; if [ -r include/generated/version_autogenerated.h ] && cmp -s include/generated/version_autogenerated.h include/generated/version_autogenerated.h.tmp; then rm -f include/generated/version_autogenerated.h.tmp; else : '  UPD     include/generated/version_autogenerated.h'; mv -f include/generated/version_autogenerated.h.tmp include/generated/version_autogenerated.h; fi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=.
set -e; mkdir -p include/generated/; 	(set -e; echo "#ifndef __GENERIC_ASM_OFFSETS_H__"; echo "#define __GENERIC_ASM_OFFSETS_H__"; echo "/*"; echo " * DO NOT MODIFY."; echo " *"; echo " * This file was generated by Kbuild"; echo " */"; echo ""; sed -ne 	"s:[[:space:]]*\.ascii[[:space:]]*\"\(.*\)\":\1:; /^->/{s:->#\(.*\):/* \1 */:; s:^->\([^ ]*\) [\$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; s:^->\([^ ]*\) [\$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; s:->::; p;}"; echo ""; echo "#endif" ) < lib/asm-offsets.s > include/generated/generic-asm-offsets.h.tmp; if [ -r include/generated/generic-asm-offsets.h ] && cmp -s include/generated/generic-asm-offsets.h include/generated/generic-asm-offsets.h.tmp; then rm -f include/generated/generic-asm-offsets.h.tmp; else : '  UPD     include/generated/generic-asm-offsets.h'; mv -f include/generated/generic-asm-offsets.h.tmp include/generated/generic-asm-offsets.h; fi
set -e; mkdir -p include/generated/; 	(set -e; echo "#ifndef __ASM_OFFSETS_H__"; echo "#define __ASM_OFFSETS_H__"; echo "/*"; echo " * DO NOT MODIFY."; echo " *"; echo " * This file was generated by Kbuild"; echo " */"; echo ""; sed -ne 	"s:[[:space:]]*\.ascii[[:space:]]*\"\(.*\)\":\1:; /^->/{s:->#\(.*\):/* \1 */:; s:^->\([^ ]*\) [\$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; s:^->\([^ ]*\) [\$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; s:->::; p;}"; echo ""; echo "#endif" ) < arch/arm/lib/asm-offsets.s > include/generated/asm-offsets.h.tmp; if [ -r include/generated/asm-offsets.h ] && cmp -s include/generated/asm-offsets.h include/generated/asm-offsets.h.tmp; then rm -f include/generated/asm-offsets.h.tmp; else : '  UPD     include/generated/asm-offsets.h'; mv -f include/generated/asm-offsets.h.tmp include/generated/asm-offsets.h; fi
#构建主机工具 ；mkenvimage: 处理 U-Boot 环境变量的工具
#mkimage: 关键工具。用于创建各种格式的镜像文件，特别是 FIT (Flattened Image Tree) 镜像
#dumpimage: 用于查看和提取镜像文件信息的工具
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=tools
  cc -Wp,-MD,tools/.mkenvimage.o.d -Itools -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -include /project/sophon/u-boot-2021.10/include/compiler.h -idirafterinclude -idirafter/project/sophon/u-boot-2021.10/include -idirafter/project/sophon/u-boot-2021.10/include/cvitek -idirafter/project/sophon/u-boot-2021.10/arch/arm/include  -I/project/sophon/u-boot-2021.10/scripts/dtc/libfdt  -I/project/sophon/u-boot-2021.10/tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -std=gnu99 -c -o tools/mkenvimage.o /project/sophon/u-boot-2021.10/tools/mkenvimage.c
  cc -Wp,-MD,tools/.fit_image.o.d -Itools -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -include /project/sophon/u-boot-2021.10/include/compiler.h -idirafterinclude -idirafter/project/sophon/u-boot-2021.10/include -idirafter/project/sophon/u-boot-2021.10/include/cvitek -idirafter/project/sophon/u-boot-2021.10/arch/arm/include  -I/project/sophon/u-boot-2021.10/scripts/dtc/libfdt  -I/project/sophon/u-boot-2021.10/tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -std=gnu99 -DMKIMAGE_DTC=\""dtc"\" -c -o tools/fit_image.o /project/sophon/u-boot-2021.10/tools/fit_image.c
  cc -Wp,-MD,tools/.image-host.o.d -Itools -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -include /project/sophon/u-boot-2021.10/include/compiler.h -idirafterinclude -idirafter/project/sophon/u-boot-2021.10/include -idirafter/project/sophon/u-boot-2021.10/include/cvitek -idirafter/project/sophon/u-boot-2021.10/arch/arm/include  -I/project/sophon/u-boot-2021.10/scripts/dtc/libfdt  -I/project/sophon/u-boot-2021.10/tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -std=gnu99 -c -o tools/image-host.o /project/sophon/u-boot-2021.10/tools/image-host.c
  cc -Wp,-MD,tools/.dumpimage.o.d -Itools -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -include /project/sophon/u-boot-2021.10/include/compiler.h -idirafterinclude -idirafter/project/sophon/u-boot-2021.10/include -idirafter/project/sophon/u-boot-2021.10/include/cvitek -idirafter/project/sophon/u-boot-2021.10/arch/arm/include  -I/project/sophon/u-boot-2021.10/scripts/dtc/libfdt  -I/project/sophon/u-boot-2021.10/tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -std=gnu99 -c -o tools/dumpimage.o /project/sophon/u-boot-2021.10/tools/dumpimage.c
  cc -Wp,-MD,tools/.mkimage.o.d -Itools -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -include /project/sophon/u-boot-2021.10/include/compiler.h -idirafterinclude -idirafter/project/sophon/u-boot-2021.10/include -idirafter/project/sophon/u-boot-2021.10/include/cvitek -idirafter/project/sophon/u-boot-2021.10/arch/arm/include  -I/project/sophon/u-boot-2021.10/scripts/dtc/libfdt  -I/project/sophon/u-boot-2021.10/tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -std=gnu99 -c -o tools/mkimage.o /project/sophon/u-boot-2021.10/tools/mkimage.c
  cc   -o tools/mkenvimage tools/mkenvimage.o tools/os_support.o tools/lib/crc32.o   
  cc   -o tools/dumpimage tools/aisimage.o tools/atmelimage.o tools/fit_common.o tools/fit_image.o tools/image-host.o tools/common/image-fit.o tools/common/fdt_region.o tools/common/bootm.o tools/lib/crc32.o tools/default_image.o tools/lib/fdtdec_common.o tools/lib/fdtdec.o tools/common/image.o tools/imagetool.o tools/imximage.o tools/imx8image.o tools/imx8mimage.o tools/lib/md5.o tools/lpc32xximage.o tools/mxsimage.o tools/omapimage.o tools/os_support.o tools/pblimage.o tools/pbl_crc32.o tools/vybridimage.o tools/stm32image.o tools/lib/rc4.o tools/rkcommon.o tools/rkimage.o tools/rksd.o tools/rkspi.o tools/socfpgaimage.o tools/sunxi_egon.o tools/lib/crc16.o tools/lib/hash-checksum.o tools/lib/sha1.o tools/lib/sha256.o tools/lib/sha512.o tools/common/hash.o tools/ublimage.o tools/zynqimage.o tools/zynqmpimage.o tools/zynqmpbif.o tools/libfdt/fdt.o tools/libfdt/fdt_ro.o tools/libfdt/fdt_wip.o tools/libfdt/fdt_sw.o tools/libfdt/fdt_rw.o tools/libfdt/fdt_strerror.o tools/libfdt/fdt_empty_tree.o tools/libfdt/fdt_addresses.o tools/libfdt/fdt_overlay.o tools/gpimage.o tools/gpimage-common.o tools/mtk_image.o tools/dumpimage.o   
  cc   -o tools/mkimage tools/aisimage.o tools/atmelimage.o tools/fit_common.o tools/fit_image.o tools/image-host.o tools/common/image-fit.o tools/common/fdt_region.o tools/common/bootm.o tools/lib/crc32.o tools/default_image.o tools/lib/fdtdec_common.o tools/lib/fdtdec.o tools/common/image.o tools/imagetool.o tools/imximage.o tools/imx8image.o tools/imx8mimage.o tools/lib/md5.o tools/lpc32xximage.o tools/mxsimage.o tools/omapimage.o tools/os_support.o tools/pblimage.o tools/pbl_crc32.o tools/vybridimage.o tools/stm32image.o tools/lib/rc4.o tools/rkcommon.o tools/rkimage.o tools/rksd.o tools/rkspi.o tools/socfpgaimage.o tools/sunxi_egon.o tools/lib/crc16.o tools/lib/hash-checksum.o tools/lib/sha1.o tools/lib/sha256.o tools/lib/sha512.o tools/common/hash.o tools/ublimage.o tools/zynqimage.o tools/zynqmpimage.o tools/zynqmpbif.o tools/libfdt/fdt.o tools/libfdt/fdt_ro.o tools/libfdt/fdt_wip.o tools/libfdt/fdt_sw.o tools/libfdt/fdt_rw.o tools/libfdt/fdt_strerror.o tools/libfdt/fdt_empty_tree.o tools/libfdt/fdt_addresses.o tools/libfdt/fdt_overlay.o tools/gpimage.o tools/gpimage-common.o tools/mtk_image.o tools/mkimage.o   
#编译目标代码
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=arch/arm/cpu
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=arch/arm/cpu/armv8
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=arch/arm/lib
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=board/cvitek/cv186x
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=cmd
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=common
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=disk
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers
  aarch64-none-linux-gnu-gcc -Wp,-MD,board/cvitek/cv186x/.board.o.d  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -Iinclude  -I/project/sophon/u-boot-2021.10/include  -I/project/sophon/u-boot-2021.10/include/cvitek  -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -I/project/sophon/u-boot-2021.10/board/cvitek/cv186x -Iboard/cvitek/cv186x -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394 -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT  -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned -D__ARM__ -fno-pic -mstrict-align -ffunction-sections -fdata-sections -fno-common -ffixed-r9 -fno-common -ffixed-x18 -pipe -march=armv8-a -D__LINUX_ARM_ARCH__=8    -DKBUILD_BASENAME='"board"'  -DKBUILD_MODNAME='"board"' -c -o board/cvitek/cv186x/board.o /project/sophon/u-boot-2021.10/board/cvitek/cv186x/board.c
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/cvi_usb
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/dma
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/adc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/gpio
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/ata
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/axi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/block
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/bus
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/net
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/cache
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/core
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/dma/ti
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/crypto
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/net/phy
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/dfu
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/firmware
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/i2c
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/input
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/led
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mailbox
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/memory
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/battery
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/crypto/fsl
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/misc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/crypto/rsa_mod_exp
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mmc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mtd
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/domain
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/net/mscc_eswitch
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/pwm
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/net/qe
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/reset
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/net/ti
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/rtc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/fuel_gauge
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/scsi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=common/init
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/smem
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/soc
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/mfd
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/sound
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/spmi
  aarch64-none-linux-gnu-gcc -Wp,-MD,common/.main.o.d  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -Iinclude  -I/project/sophon/u-boot-2021.10/include  -I/project/sophon/u-boot-2021.10/include/cvitek  -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -I/project/sophon/u-boot-2021.10/common -Icommon -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394 -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT  -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned -D__ARM__ -fno-pic -mstrict-align -ffunction-sections -fdata-sections -fno-common -ffixed-r9 -fno-common -ffixed-x18 -pipe -march=armv8-a -D__LINUX_ARM_ARCH__=8    -DKBUILD_BASENAME='"main"'  -DKBUILD_MODNAME='"main"' -c -o common/main.o /project/sophon/u-boot-2021.10/common/main.c
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/thermal
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/pmic
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/ufs
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mtd/nand
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/video
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mtd/onenand
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/mtd/spi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/watchdog
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/power/regulator
  aarch64-none-linux-gnu-gcc -Wp,-MD,cmd/.version.o.d  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -Iinclude  -I/project/sophon/u-boot-2021.10/include  -I/project/sophon/u-boot-2021.10/include/cvitek  -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -I/project/sophon/u-boot-2021.10/cmd -Icmd -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394 -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT  -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned -D__ARM__ -fno-pic -mstrict-align -ffunction-sections -fdata-sections -fno-common -ffixed-r9 -fno-common -ffixed-x18 -pipe -march=armv8-a -D__LINUX_ARM_ARCH__=8    -DKBUILD_BASENAME='"version"'  -DKBUILD_MODNAME='"version"' -c -o cmd/version.o /project/sophon/u-boot-2021.10/cmd/version.c
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/serial
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/video/bridge
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/video/sunxi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/video/ti
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/spi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/cdns3
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/common
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/dwc3
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/emul
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/eth
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/host
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=cmd/arm
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/mtu3
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/musb-new
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/musb
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/phy
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=drivers/usb/ulpi
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=env
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=fs
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=net
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=fs/ext4
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=fs/fat
#编译后，aarch64-none-linux-gnu-ar 将对象文件打包成静态库 (built-in.o)
   rm -f cmd/built-in.o; aarch64-none-linux-gnu-ar cDPrsT cmd/built-in.o cmd/boot.o cmd/bootm.o cmd/help.o cmd/panic.o cmd/version.o cmd/adc.o cmd/blk_common.o cmd/source.o cmd/bdinfo.o cmd/blkcache.o cmd/bootefi.o cmd/booti.o cmd/cache.o cmd/echo.o cmd/elf.o cmd/exit.o cmd/ext4.o cmd/ext2.o cmd/fat.o cmd/fdt.o cmd/flash.o cmd/cvi_update.o cmd/cvi_utask.o cmd/fs.o cmd/gpio.o cmd/led.o cmd/load.o cmd/mem.o cmd/mii.o cmd/mdio.o cmd/sleep.o cmd/mmc.o cmd/mmcbcbx.o cmd/bm_savelog.o cmd/net.o cmd/part.o cmd/pwm.o cmd/pxe.o cmd/pxe_utils.o cmd/setexpr.o cmd/sysboot.o cmd/test.o cmd/unzip.o cmd/usb.o cmd/disk.o cmd/gpt.o cmd/otp.o cmd/arm/built-in.o cmd/nvedit.o
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/crypto
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/efi_driver
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/efi_loader
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/libfdt
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/lzma
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=lib/zlib
  aarch64-none-linux-gnu-gcc -Wp,-MD,lib/.smbios.o.d  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -Iinclude  -I/project/sophon/u-boot-2021.10/include  -I/project/sophon/u-boot-2021.10/include/cvitek  -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -I/project/sophon/u-boot-2021.10/lib -Ilib -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394 -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT  -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned -D__ARM__ -fno-pic -mstrict-align -ffunction-sections -fdata-sections -fno-common -ffixed-r9 -fno-common -ffixed-x18 -pipe -march=armv8-a -D__LINUX_ARM_ARCH__=8    -DKBUILD_BASENAME='"smbios"'  -DKBUILD_MODNAME='"smbios"' -c -o lib/smbios.o /project/sophon/u-boot-2021.10/lib/smbios.c
   rm -f common/built-in.o; aarch64-none-linux-gnu-ar cDPrsT common/built-in.o common/init/built-in.o common/main.o common/exports.o common/cli_hush.o common/autoboot.o common/board_f.o common/board_r.o common/bootm.o common/bootm_os.o common/fdt_support.o common/miiphyutil.o common/usb.o common/usb_hub.o common/usb_storage.o common/splash.o common/menu.o common/cli_readline.o common/cli_simple.o common/console.o common/dlmalloc.o common/malloc_simple.o common/image.o common/hash.o common/image-fdt.o common/image-fit.o common/boot_fit.o common/common_fit.o common/memsize.o common/stdio.o common/cli.o common/command.o common/s_record.o common/xyzModem.o
  aarch64-none-linux-gnu-gcc -Wp,-MD,lib/.display_options.o.d  -nostdinc -isystem /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/include -Iinclude  -I/project/sophon/u-boot-2021.10/include  -I/project/sophon/u-boot-2021.10/include/cvitek  -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h  -I/project/sophon/u-boot-2021.10/lib -Ilib -D__KERNEL__ -D__UBOOT__ -DCONFIG_USE_DEFAULT_ENV=y -DCVICHIP=bm1688 -DCVIBOARD=wevb_emmc -DBM1688_WEVB_EMMC -DMIPI_PANEL_HX8394 -Wall -Wstrict-prototypes -Wno-format-security -fno-builtin -ffreestanding -std=gnu11 -fshort-wchar -fno-strict-aliasing -Werror -fno-PIE -DCONFIG_EMMC_SUPPORT  -I/project/sophon/u-boot-2021.10/include/cvitek -Os -fno-stack-protector -fno-delete-null-pointer-checks -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-maybe-uninitialized -fmacro-prefix-map=/project/sophon/u-boot-2021.10/= -g -fstack-usage -Wno-format-nonliteral -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=date-time -Wno-packed-not-aligned -D__ARM__ -fno-pic -mstrict-align -ffunction-sections -fdata-sections -fno-common -ffixed-r9 -fno-common -ffixed-x18 -pipe -march=armv8-a -D__LINUX_ARM_ARCH__=8    -DKBUILD_BASENAME='"display_options"'  -DKBUILD_MODNAME='"display_options"' -c -o lib/display_options.o /project/sophon/u-boot-2021.10/lib/display_options.c
   rm -f lib/built-in.o; aarch64-none-linux-gnu-ar cDPrsT lib/built-in.o lib/efi_driver/built-in.o lib/efi_loader/built-in.o lib/lzma/built-in.o lib/libfdt/built-in.o lib/crypto/built-in.o lib/charset.o lib/crc8.o lib/crc16.o lib/fdtdec_common.o lib/smbios.o lib/ldiv.o lib/net_utils.o lib/rc4.o lib/list_sort.o lib/md5.o lib/hash-checksum.o lib/sha1.o lib/sha256.o lib/zlib/built-in.o lib/gunzip.o lib/lz4_wrapper.o lib/fdtdec.o lib/qsort.o lib/hashtable.o lib/errno.o lib/display_options.o lib/crc32.o lib/ctype.o lib/div64.o lib/hang.o lib/linux_compat.o lib/linux_string.o lib/lmb.o lib/membuff.o lib/slre.o lib/string.o lib/tables_csum.o lib/time.o lib/hexdump.o lib/uuid.o lib/rand.o lib/panic.o lib/vsprintf.o lib/strto.o lib/date.o lib/rtc-lib.o lib/elf.o
   rm -f board/cvitek/cv186x/built-in.o; aarch64-none-linux-gnu-ar cDPrsT board/cvitek/cv186x/built-in.o board/cvitek/cv186x/board.o
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=examples
#将所有编译好的对象文件 (built-in.o) 和库链接在一起，生成最终的 ELF 格式可执行文件 u-boot
  aarch64-none-linux-gnu-ld.bfd  -pie  --gc-sections -Bstatic  --no-dynamic-linker --build-id=none -Ttext 0x1000a0000 -o u-boot -T u-boot.lds arch/arm/cpu/armv8/start.o --whole-archive  arch/arm/cpu/built-in.o  arch/arm/cpu/armv8/built-in.o  arch/arm/lib/built-in.o  board/cvitek/cv186x/built-in.o  cmd/built-in.o  common/built-in.o  disk/built-in.o  drivers/built-in.o  drivers/cvi_usb/built-in.o  drivers/dma/built-in.o  drivers/gpio/built-in.o  drivers/net/built-in.o  drivers/net/phy/built-in.o  drivers/power/built-in.o  drivers/power/battery/built-in.o  drivers/power/domain/built-in.o  drivers/power/fuel_gauge/built-in.o  drivers/power/mfd/built-in.o  drivers/power/pmic/built-in.o  drivers/power/regulator/built-in.o  drivers/serial/built-in.o  drivers/spi/built-in.o  drivers/usb/cdns3/built-in.o  drivers/usb/common/built-in.o  drivers/usb/dwc3/built-in.o  drivers/usb/emul/built-in.o  drivers/usb/eth/built-in.o  drivers/usb/host/built-in.o  drivers/usb/mtu3/built-in.o  drivers/usb/musb-new/built-in.o  drivers/usb/musb/built-in.o  drivers/usb/phy/built-in.o  drivers/usb/ulpi/built-in.o  env/built-in.o  fs/built-in.o  lib/built-in.o  net/built-in.o --no-whole-archive -L /project/sophon/host-tools/gcc/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1 -lgcc -Map u-boot.map;  true
#从 ELF 文件 u-boot 中提取纯二进制代码和数据，生成 u-boot-nodtb.bin。这个文件还不包含设备树 blob (DTB)
  aarch64-none-linux-gnu-objcopy --gap-fill=0xff  -j .text -j .secure_text -j .secure_data -j .rodata -j .data -j .u_boot_list -j .rela.dyn -j .got -j .got.plt -j .binman_sym_table -j .text_rest -j .dtb.init.rodata -j .efi_runtime -j .efi_runtime_rel -O srec u-boot u-boot.srec
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=dts dtbs
  aarch64-none-linux-gnu-objcopy --gap-fill=0xff  -j .text -j .secure_text -j .secure_data -j .rodata -j .data -j .u_boot_list -j .rela.dyn -j .got -j .got.plt -j .binman_sym_table -j .text_rest -j .dtb.init.rodata -j .efi_runtime -j .efi_runtime_rel -O binary   u-boot u-boot-nodtb.bin && {  echo '  start=$(aarch64-none-linux-gnu-nm  | grep __rel_dyn_start | cut -f 1 -d '\'' '\''); end=$(aarch64-none-linux-gnu-nm  | grep __rel_dyn_end | cut -f 1 -d '\'' '\''); tools/relocate-rela   $start $end'; start=$(aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x1000a0000 $start $end; } || { rm -f u-boot-nodtb.bin; false; }
#编译设备树源文件
make -f /project/sophon/u-boot-2021.10/scripts/Makefile.build obj=arch/arm/dts dtbs
  aarch64-none-linux-gnu-objdump -t u-boot > u-boot.sym
  start=$(aarch64-none-linux-gnu-nm  | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(aarch64-none-linux-gnu-nm  | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela   $start $end
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/bm1688_wevb_emmc.dts; ) > arch/arm/dts/.bm1688_wevb_emmc.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.bm1688_wevb_emmc.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.bm1688_wevb_emmc.dtb.dts.tmp arch/arm/dts/.bm1688_wevb_emmc.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/bm1688_wevb_emmc.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.bm1688_wevb_emmc.dtb.d.dtc.tmp arch/arm/dts/.bm1688_wevb_emmc.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.bm1688_wevb_emmc.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.bm1688_wevb_emmc.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/bm1688_wevb_emmc.dts:" arch/arm/dts/.bm1688_wevb_emmc.dtb.d.pre.tmp arch/arm/dts/.bm1688_wevb_emmc.dtb.d.dtc.tmp > arch/arm/dts/.bm1688_wevb_emmc.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b1_4G.dts; ) > arch/arm/dts/.cv186ah_se9b1_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9b1_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9b1_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9b1_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9b1_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9b1_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9b1_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9b1_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9b1_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b1_4G.dts:" arch/arm/dts/.cv186ah_se9b1_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9b1_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9b1_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9v1_4G.dts; ) > arch/arm/dts/.cv186ah_se9v1_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9v1_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9v1_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9v1_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9v1_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9v1_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9v1_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9v1_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9v1_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9v1_4G.dts:" arch/arm/dts/.cv186ah_se9v1_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9v1_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9v1_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b2_4G.dts; ) > arch/arm/dts/.cv186ah_se9b2_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9b2_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9b2_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9b2_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9b2_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9b2_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9b2_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9b2_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9b2_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b2_4G.dts:" arch/arm/dts/.cv186ah_se9b2_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9b2_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9b2_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b3_4G.dts; ) > arch/arm/dts/.cv186ah_se9b3_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9b3_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9b3_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9b3_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9b3_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9b3_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9b3_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9b3_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9b3_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b3_4G.dts:" arch/arm/dts/.cv186ah_se9b3_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9b3_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9b3_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b4_4G.dts; ) > arch/arm/dts/.cv186ah_se9b4_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9b4_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9b4_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9b4_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9b4_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9b4_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9b4_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9b4_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9b4_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9b4_4G.dts:" arch/arm/dts/.cv186ah_se9b4_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9b4_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9b4_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9k1_4G.dts; ) > arch/arm/dts/.cv186ah_se9k1_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_se9k1_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_se9k1_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_se9k1_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_se9k1_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_se9k1_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_se9k1_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_se9k1_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_se9k1_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_se9k1_4G.dts:" arch/arm/dts/.cv186ah_se9k1_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_se9k1_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_se9k1_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_sm9v1_4G.dts; ) > arch/arm/dts/.cv186ah_sm9v1_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_sm9v1_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_sm9v1_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_sm9v1_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_sm9v1_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_sm9v1_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_sm9v1_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_sm9v1_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_sm9v1_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_sm9v1_4G.dts:" arch/arm/dts/.cv186ah_sm9v1_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_sm9v1_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_sm9v1_4G.dtb.d
  mkdir -p arch/arm/dts/ ; (cat /project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_wevb_4G.dts; ) > arch/arm/dts/.cv186ah_wevb_4G.dtb.pre.tmp; cc -E -Wp,-MD,arch/arm/dts/.cv186ah_wevb_4G.dtb.d.pre.tmp -nostdinc -I/project/sophon/u-boot-2021.10/arch/arm/dts -I/project/sophon/u-boot-2021.10/arch/arm/dts/include -Iinclude -I/project/sophon/u-boot-2021.10/include -I/project/sophon/u-boot-2021.10/arch/arm/include -include /project/sophon/u-boot-2021.10/include/linux/kconfig.h -D__ASSEMBLY__ -undef -D__DTS__ -D__UBOOT__ -x assembler-with-cpp -o arch/arm/dts/.cv186ah_wevb_4G.dtb.dts.tmp arch/arm/dts/.cv186ah_wevb_4G.dtb.pre.tmp ; ./scripts/dtc/dtc -O dtb -o arch/arm/dts/cv186ah_wevb_4G.dtb -b 0 -i /project/sophon/u-boot-2021.10/arch/arm/dts/  -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -a 0x8 -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-simple_bus_reg -Wno-pci_device_reg -Wno-pci_bridge -Wno-pci_device_bus_num  -d arch/arm/dts/.cv186ah_wevb_4G.dtb.d.dtc.tmp arch/arm/dts/.cv186ah_wevb_4G.dtb.dts.tmp || (echo "Check /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/arch/arm/dts/.cv186ah_wevb_4G.dtb.pre.tmp for errors" && false) ; sed "s:arch/arm/dts/.cv186ah_wevb_4G.dtb.pre.tmp:/project/sophon/u-boot-2021.10/arch/arm/dts/cv186ah_wevb_4G.dts:" arch/arm/dts/.cv186ah_wevb_4G.dtb.d.pre.tmp arch/arm/dts/.cv186ah_wevb_4G.dtb.d.dtc.tmp > arch/arm/dts/.cv186ah_wevb_4G.dtb.d
test -e arch/arm/dts/bm1688_wevb_emmc.dtb || (						\
echo >&2;							\
echo >&2 "Device Tree Source (arch/arm/dts/bm1688_wevb_emmc.dtb) is not correctly specified.";	\
echo >&2 "Please define 'CONFIG_DEFAULT_DEVICE_TREE'";		\
echo >&2 "or build with 'DEVICE_TREE=<device_tree>' argument";	\
echo >&2;							\
/bin/false)
  cat arch/arm/dts/bm1688_wevb_emmc.dtb > dts/dt.dtb
#创建 FIT 镜像并生成最终二进制文件
  ./tools/mkimage -f auto -A arm -T firmware -C none -O u-boot -a 0 -e 0 -E -b arch/arm/dts/cv186ah_se9b1_4G.dtb -b arch/arm/dts/cv186ah_se9v1_4G.dtb -b arch/arm/dts/cv186ah_se9b2_4G.dtb -b arch/arm/dts/cv186ah_se9b3_4G.dtb -b arch/arm/dts/cv186ah_sm9v1_4G.dtb -b arch/arm/dts/cv186ah_wevb_4G.dtb -d /dev/null -B 0x8 -d dts/dt.dtb fit-dtb.blob >/dev/null  && cat /dev/null
  cp dts/dt.dtb u-boot.dtb
  cat u-boot-nodtb.bin fit-dtb.blob > u-boot-fit-dtb.bin
  cp u-boot-fit-dtb.bin u-boot.bin
aarch64-none-linux-gnu-objcopy -I binary -B aarch64 -O elf64-littleaarch64 u-boot.bin u-boot-elf.o
  aarch64-none-linux-gnu-ld.bfd u-boot-elf.o -o u-boot.elf -T u-boot-elf.lds --defsym="_start"=0x1000a0000 -Ttext=0x1000a0000
make[2]: Leaving directory '/project/sophon/u-boot-2021.10/build/edge_wevb_emmc'
make[1]: Leaving directory '/project/sophon/u-boot-2021.10'
cat /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/u-boot.bin > /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/u-boot-raw.bin
aarch64-none-linux-gnu-objdump -S /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/u-boot > /project/sophon/u-boot-2021.10/build/edge_wevb_emmc/u-boot.dis




#fsbl-build
[1;36;40m  [TARGET] fsbl-build [0m
mkdir -p /project/sophon/fsbl/build
ln -snrf -t /project/sophon/fsbl/build /project/sophon/build/output/edge_wevb_emmc/cvi_board_memmap.h
make -j48 -C /project/sophon/fsbl SPD=opteed O=/project/sophon/fsbl/build/edge_wevb_emmc BLCP_2ND_PATH= \
	LOADER_2ND_PATH=/project/sophon/u-boot-2021.10/build/edge_wevb_emmc/u-boot-raw.bin
make[1]: Entering directory '/project/sophon/fsbl'
[1;34;40m  MAKECMDGOALS  [0m
Including services/spd/opteed/opteed.mk
[1;34;40m  [VAR] CHIP_ARCH=cv186x [0m
[1;34;40m  [VAR] BOOT_CPU=aarch64 [0m
Including drivers/auth/mbedtls/mbedtls_crypto.mk
[1;34;40m  [VAR] DDR_CFG=ddr_auto [0m
[1;34;40m  [VAR] TEST_FROM_SPINOR1=0 [0m
[1;34;40m  [VAR] PAGE_SIZE_64KB= [0m
[1;34;40m  TARGET bl31 [0m
[1;34;40m  TARGET bl32 [0m
[1;34;40m  TARGET bl2 [0m
[1;34;40m  TARGET blmacros [0m
[1;34;40m  TARGET gen-chip-conf [0m
[1;34;40m  TARGET blmacros-env [0m
[1;34;40m  TARGET fip-all [0m
  [GEN] fip.bin
  [LS]  -rw-r--r-- 1 root root 435712 Aug 27 18:31 /project/sophon/fsbl/build/edge_wevb_emmc/fip.bin
make[1]: Leaving directory '/project/sophon/fsbl'
cp /project/sophon/fsbl/build/edge_wevb_emmc/fip.bin /project/sophon/install/soc_edge_wevb_emmc/
